export const loginApi = 'http://localhost:4000/login'
export const dashboardInfoApi = 'http://localhost:4000/count'
export const top3Api = 'http://localhost:4000/countkecamatan'
export const getKecamatanApi = 'http://localhost:4000/kecamatan'
export const getLaporan = 'http://localhost:4000/laporan?'
export const getLaporanToCount = 'http://localhost:4000/laporanall'